//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Videos.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class playlist_filtros
    {
        public int id { get; set; }
        public string tipo { get; set; }
        public string valor { get; set; }
        public int id_playlist { get; set; }
    
        public virtual playlist playlist { get; set; }
    }
}
