//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Videos.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class video
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public video()
        {
            this.video_artista = new HashSet<video_artista>();
            this.video_musica = new HashSet<video_musica>();
            this.video_tag = new HashSet<video_tag>();
        }
    
        public int id { get; set; }
        public string titulo { get; set; }
        public string caminho { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public string extensao { get; set; }
        public int id_tipo { get; set; }
        public string duracao { get; set; }
        public string resolucao { get; set; }
        public string formato_video { get; set; }
        public string fps { get; set; }
        public string canais_audio { get; set; }
        public string formato_audio { get; set; }
        public bool favorito { get; set; }
        public Nullable<long> tamanho { get; set; }
        public int id_categoria { get; set; }
    
        public virtual tipo tipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<video_artista> video_artista { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<video_musica> video_musica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<video_tag> video_tag { get; set; }
        public virtual categoria categoria { get; set; }
    }
}
