//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Videos.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VideosEntities : DbContext
    {
        public VideosEntities()
            : base("name=VideosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<artista> artista { get; set; }
        public virtual DbSet<musica> musica { get; set; }
        public virtual DbSet<tag> tag { get; set; }
        public virtual DbSet<tipo> tipo { get; set; }
        public virtual DbSet<video> video { get; set; }
        public virtual DbSet<video_artista> video_artista { get; set; }
        public virtual DbSet<video_musica> video_musica { get; set; }
        public virtual DbSet<video_tag> video_tag { get; set; }
    }
}
