//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Videos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoEntity
    {
        public int id { get; set; }
        public string titulo { get; set; }
        public string caminho { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public int tipo { get; set; }
        public int artista { get; set; }
        public string extensao { get; set; }
    
        public virtual ArtistaEntity Artista1 { get; set; }
        public virtual TipoEntity Tipo1 { get; set; }
    }
}
